name: QA

on:
  workflow_call:
    inputs:
      runner:
        description: Runner label to use for NodeJS checks.
        required: false
        type: string
        default: ubuntu-latest

jobs:
  linting:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run lint

#  unit:
#    runs-on: ${{ inputs.runner }}
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install dependencies
#        run: npm install
#      - name: Run unit tests with coverage
#        run: npm run coverage
